### PR TITLE
transcribed page 114

### PR DESCRIPTION
**Pull request by decuser**

### CODE REVIEW

**Comment by decuser** [comment]
added a couple more pages - page 116 is probably readable by somebody who knows the code, but I couldn't make heads or tails out of it.

**Comment by decuser** [comment]
added the last two, committed to in this pass.

**Comment by larsbrinkhoff** [comment]
Thanks!  Please use _ for left arrow, and ^ for up arrow.  The arrows are the ASCII-63 versions of those two characters.

**Comment by larsbrinkhoff** [comment]
And please read the information here: https://github.com/PDP-6/ITS/issues/2

**Comment by larsbrinkhoff** [comment]
Thanks!  I'll get this merged when @sebras has updated his pull requests.

**Comment by larsbrinkhoff** [comment]
I have rebased your changes on top of @sebras'.  Now we can see the differences in the two transcriptions.

**Comment by larsbrinkhoff** [comment]
I have reviewed all your changes now.  You found some typos, so thanks very much!

**Comment by sebras** [comment]
> Thanks! I'll get this merged when @sebras has updated his pull requests.

Sorry, I was busy yesterday. It looks like you've already done all the updating of my pull requests, if I read the github PR status correctly.

Also @decuser, good work! :-)

**Pull request merged**
