### PR TITLE
Transcribe LISP TECOSM and TECO DOC.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This seems to be some kind of structure editor.  Unfortunately, some lines are truncated so code is missing.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@sebras, TECO DOC has an unbalanced parenthesis.  Can you see if I missed any?

**Comment by sebras** [comment]
@larsbrinkhoff  I fixed the typos in TECO.DOC, but given the frequencey perhaps I should check TECOSM too?

**Comment by larsbrinkhoff** [comment]
Yes, please.  Both documents.

**Comment by sebras** [comment]
I have fixed the typos in TECOSM, but I still have a whitespace patch pending. Let me get to that before we rebase and merge this PR. :)

**Comment by larsbrinkhoff** [comment]
Sure, take your time and let me know when it's all done.  I can't believe I made so many typos...

**Comment by sebras** [comment]
Alright, all my fixes are on your branch now. I have nothing further for TECO.DOC and LISP TECOSM. Will you do the honours and rebase and merge @larsbrinkhoff ?

**Review by sebras — APPROVED** [review]
After my fixes I think this is perfect! :)

**Pull request merged**
